"""empty message

Revision ID: 9f684dc131ea
Revises: 5686d81f4e87
Create Date: 2024-05-04 10:24:12.278314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f684dc131ea'
down_revision = '5686d81f4e87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_panel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('panel')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('panel',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('website', sa.VARCHAR(length=255), nullable=True),
    sa.Column('username', sa.VARCHAR(length=255), nullable=True),
    sa.Column('password', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user_panel')
    # ### end Alembic commands ###
