"""empty message

Revision ID: c4282e9bc6d9
Revises: 9f684dc131ea
Create Date: 2024-05-04 15:02:40.878772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4282e9bc6d9'
down_revision = '9f684dc131ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_panel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_panel', schema=None) as batch_op:
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
